Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 50

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
  SupportedStyles:
    - empty_lines
    - empty_lines_except_namespace
    - no_empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - empty_lines_except_namespace
    - no_empty_lines