Style/RedundantReturn:
  # When true allows code like `return x, y`.
  AllowMultipleReturnValues: true

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 50

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
  SupportedStyles:
    - empty_lines
    - empty_lines_except_namespace
    - no_empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - empty_lines_except_namespace
    - no_empty_lines

Style/WordArray:
  EnforcedStyle: brackets
  SupportedStyles:
    # percent style: %w(word1 word2)
    - percent
    # bracket style: ['word1', 'word2']
    - brackets